modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="sikunbenssololeveling"
version="1.0.0"
displayName="SikunBensSoloLeveling"
credits="https://www.curseforge.com/members/siikkuu/"
displayURL="https://www.curseforge.com/members/siikkuu/"
authors="Siku, TechnoBen"
description='''
A mod based on solo leveling, the player can go through dungeons and become stronger and stronger!
'''

[[dependencies.sikunbenssololeveling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.sikunbenssololeveling]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sikunbenssololeveling]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sikunbenssololeveling]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

